# Preprocessing Data 
- Nama : Mufida Rahayu
- NIM  : A11.2020.12918

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [49]:
dataset = pd.read_csv('/content/music_genre.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [50]:
print(x)

[['Bruno Mars' "That's What I Like (feat. Gucci Mane)" 60.0 ... 134.071
  234596.0 4]
 ['Boston' 'Hitch a Ride' 54.0 ... 116.454 251733.0 4]
 ['The Raincoats' 'No Side to Fall In' 35.0 ... 147.681 109667.0 4]
 ...
 ['Smash Hit Combo' 'Peine perdue' 34.0 ... 105.0 216222.0 4]
 ['Beherit' "Salomon's Gate" 29.0 ... 131.363 219693.0 4]
 ['The Raconteurs' 'Broken Boy Soldier' 43.0 ... 138.102 182227.0 4]]


In [51]:
print(y)

[ 5 10  6 ...  8  8 10]


In [55]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(x[:, 2:15])
x[:, 2:15] = imputer.transform(x[:, 2:15])

In [56]:
print(x)

[['Bruno Mars' "That's What I Like (feat. Gucci Mane)" 60.0 ... 134.071
  234596.0 4]
 ['Boston' 'Hitch a Ride' 54.0 ... 116.454 251733.0 4]
 ['The Raincoats' 'No Side to Fall In' 35.0 ... 147.681 109667.0 4]
 ...
 ['Smash Hit Combo' 'Peine perdue' 34.0 ... 105.0 216222.0 4]
 ['Beherit' "Salomon's Gate" 29.0 ... 131.363 219693.0 4]
 ['The Raconteurs' 'Broken Boy Soldier' 43.0 ... 138.102 182227.0 4]]


In [61]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse_output=False), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [62]:
print(x)

[[0.0 1.0 0.0 ... 134.071 234596.0 4]
 [0.0 1.0 0.0 ... 116.454 251733.0 4]
 [0.0 1.0 0.0 ... 147.681 109667.0 4]
 ...
 [0.0 1.0 0.0 ... 105.0 216222.0 4]
 [0.0 1.0 0.0 ... 131.363 219693.0 4]
 [0.0 1.0 0.0 ... 138.102 182227.0 4]]


In [63]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [64]:
print(y)

[ 5 10  6 ...  8  8 10]


In [65]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [66]:
print(x_train)

[[0.0 1.0 0.0 ... 152.638 201194.0 4]
 [0.0 1.0 0.0 ... 79.094 229893.0 4]
 [0.0 1.0 0.0 ... 67.528 183956.0 4]
 ...
 [0.0 1.0 0.0 ... 112.963 375187.0 4]
 [0.0 1.0 0.0 ... 91.984 174585.0 4]
 [0.0 1.0 0.0 ... 141.967 182307.0 4]]


In [67]:
print(x_test)

[[0.0 1.0 0.0 ... 119.958 185916.0 4]
 [0.0 1.0 0.0 ... 82.113 269693.0 4]
 [0.0 1.0 0.0 ... 104.627 249094.0 4]
 ...
 [0.0 1.0 0.0 ... 110.615 281133.0 4]
 [0.0 1.0 0.0 ... 127.409 180433.0 4]
 [0.0 1.0 0.0 ... 139.048 4.2605 4]]


In [68]:
print(y_train)

[ 1  1 10 ...  8  5  6]


In [69]:
print(y_test)

[1 5 8 ... 6 2 0]


In [87]:
import numpy as np
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, :15] = np.array(sc.fit_transform(x_train[:, :15]))
x_test[:, :15] = sc.transform(x_test[:, :15])

In [88]:
print(x_train)

[[-0.008334780469459319 0.008334780469460795 -0.008334780469459319 ...
  152.638 201194.0 4]
 [-0.008334780469459319 0.008334780469460795 -0.008334780469459319 ...
  79.094 229893.0 4]
 [-0.008334780469459319 0.008334780469460795 -0.008334780469459319 ...
  67.528 183956.0 4]
 ...
 [-0.008334780469459319 0.008334780469460795 -0.008334780469459319 ...
  112.963 375187.0 4]
 [-0.008334780469459319 0.008334780469460795 -0.008334780469459319 ...
  91.984 174585.0 4]
 [-0.008334780469459319 0.008334780469460795 -0.008334780469459319 ...
  141.967 182307.0 4]]


In [89]:
print(x_test)

[[2.525625312605317e-15 0.9999999999999906 2.525625312605317e-15 ...
  119.958 185916.0 4]
 [2.525625312605317e-15 0.9999999999999906 2.525625312605317e-15 ...
  82.113 269693.0 4]
 [2.525625312605317e-15 0.9999999999999906 2.525625312605317e-15 ...
  104.627 249094.0 4]
 ...
 [2.525625312605317e-15 0.9999999999999906 2.525625312605317e-15 ...
  110.615 281133.0 4]
 [2.525625312605317e-15 0.9999999999999906 2.525625312605317e-15 ...
  127.409 180433.0 4]
 [2.525625312605317e-15 0.9999999999999906 2.525625312605317e-15 ...
  139.048 4.2605 4]]
